- docs/DeveloperGuide.md
Done as part of the instructions of [CS2103T Week 7 tP Task 3](https://nus-cs2103-ay2425s2.github.io/website/schedule/week7/project.html#3-update-the-dg-user-stories-glossary-nfrs-use-cases)
Add some terms to the glossary in the Developer Guide.
> Section 3: Glossary

- docs/DeveloperGuide.md
> Section 3: Non-functional requirements 

- docs/AboutUs.md
- docs/_config.yml
Fix incorrect filepath for one profile image
Change to use lowercase for image filepath
Change title in _config.yml file
Closes #43
> Fix v1.1 bugs

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/DelLastVisitCommandParser.java
- src/main/java/seedu/address/model/person/LastVisit.java
- src/test/java/seedu/address/logic/commands/DelLastVisitCommandTest.java
- src/test/java/seedu/address/logic/parser/DelLastVisitCommandParserTest.java
THIS IS A DRAFT FOR NOW, PLS DO NOT MERGE YET
Implement the `delLastVisit` cmd which sets the `LastVisit` attribute to the String `NA`.
Will check CI things and implement some tests after
> Delete Last Visit Feature

- docs/UserGuide.md
Just creating the PR first as a draft
> Update User Guide To Include `delLastVisit`

- src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java
- src/main/java/seedu/address/model/patient/Patient.java
- src/main/java/seedu/address/storage/JsonAdaptedPatient.java
- src/main/java/seedu/address/ui/PatientCard.java
- src/test/java/seedu/address/logic/commands/DelLastVisitCommandTest.java
- src/test/java/seedu/address/testutil/PatientBuilder.java
> Allow `Patient.lastVisit` to be `null`

- docs/UserGuide.md
> Update user guide to include Last Visit command

- src/main/java/seedu/address/ui/HelpWindow.java
> Update Help Link

- build.gradle
- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/ui/PatientCard.java
- src/main/java/seedu/address/ui/PatientListPanel.java
- src/main/java/seedu/address/ui/UiPart.java
> Fix incorrect FXML filepath preventing jar build

- src/main/resources/view/MainWindow.fxml
> Rename Title from `Address App` to `CareConnect`

- src/main/java/seedu/address/logic/commands/PrescribeCommand.java
- src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
- src/test/java/seedu/address/logic/commands/PrescribeCommandTest.java
- src/test/java/seedu/address/logic/commands/UnprescribeCommandTest.java
> Update result for commands

- src/main/resources/view/CareConnectTheme.css
> Fix Ui bug for when patient list is small

- src/main/java/seedu/address/logic/commands/AddCommand.java
> Fix Typo In `add` Usage Message

- docs/UserGuide.md
- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/logic/commands/DeleteCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/ExitCommand.java
- src/main/java/seedu/address/logic/commands/FindCommand.java
- src/main/java/seedu/address/logic/commands/LastVisitCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/TagCommand.java
- src/main/java/seedu/address/logic/commands/UnprescribeCommand.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/UserPrefs.java
- src/main/java/seedu/address/storage/JsonAddressBookStorage.java
- src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
- src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Rename all client visible instances of addressbook to careconnect
closes #115
> Renamed client visible instances of addressbook

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/LastVisitCommandParser.java
- Fix bug where `lastVisit` command accepts more than one date 
- Fix bug where `lastVisit` command is unclear in reporting
invalid dates
Closes #155 
Closes #153
> Bug Fix: `lastVisit` command error handling

- docs/UserGuide.md
Update part of the UG
Also to satisfy the 3 updated lines in the UG requirement
> 2025 04 01 update ug general

- src/main/java/seedu/address/logic/commands/TagCommand.java
- src/main/java/seedu/address/logic/parser/TagCommandParser.java
> Force at least 1 tag in tag cmd

- docs/diagrams/LastVisitSequenceDiagram.puml
> Add sequence diagram for LastVisit command

- src/main/java/seedu/address/logic/commands/TagCommand.java
- src/main/java/seedu/address/logic/parser/TagCommandParser.java
- src/main/java/seedu/address/model/tag/Tag.java
- src/test/java/seedu/address/logic/commands/TagCommandTest.java
- src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
> 2025 04 02 fix tag bugs

- src/main/java/seedu/address/model/tag/Tag.java
> Allow - and _ in tags

- src/main/java/seedu/address/logic/commands/UntagCommand.java
- src/main/java/seedu/address/logic/parser/UntagCommandParser.java
- src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Closes #200 and #203
Currently only closes #200
> Prevent dupe inputs in untag

- docs/UserGuide.md
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/patient/Name.java
- src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Updated error messages/success messages for `add` command accordingly
Closes #168 , #107
> Make lastvisit in add optional

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
> Add ability for add to parse medicines

- src/main/java/seedu/address/logic/commands/EditCommand.java
> Fix edit msg

- docs/_sass/minima/_base.scss
Closes #272 
Closes #273 
Closes #260 
Closes #230
> Fix bug where AB-3 is the header

- docs/UserGuide.md
> Update user guide branch

- src/main/java/seedu/address/commons/core/LogsCenter.java
> Bug Fix: Logging file still named as addressbook

- src/main/java/seedu/address/model/patient/Phone.java
> Bug Fix: No number limit enforced to phone number

- src/main/java/seedu/address/logic/commands/DelLastVisitCommand.java
Update the string since delLastVisit being set to NA was removed way back in v1.3 or v1.4
> Fix dellastvisit usage msg

- docs/DeveloperGuide.md
> Fix missing Developer Guide header

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
Prevent edit command without resulting change
> Prevent edit command without resultant change

- docs/UserGuide.md
> Update typo in UG
